// Package gin provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package gin

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ConstraintsViolation It represents a constraints violation error
type ConstraintsViolation struct {
	// Field The field that is causing the constraints violation
	Field string `json:"field"`

	// Message The human-readable constraints violation description
	Message string `json:"message"`
}

// ConstraintsViolationsError Note: It follows [RFC-7807](https://tools.ietf.org/html/rfc7807#page-9) **proposed** standard
//
// Error object returned on any failure. It can be extended to add more params
type ConstraintsViolationsError = Error

// Error Note: It follows [RFC-7807](https://tools.ietf.org/html/rfc7807#page-9) **proposed** standard
//
// Error object returned on any failure. It can be extended to add more params
type Error struct {
	// Detail A human-readable explanation specific to this occurrence of the problem
	Detail *string `json:"detail,omitempty"`

	// Status The HTTP status code generated by the origin server for this occurrence of the problem
	Status int `json:"status"`

	// Title A short, human-readable summary of the problem type
	Title string `json:"title"`
}

// Product A product
type Product struct {
	// LangEnUs Name of a product in en-US language
	LangEnUs string `json:"lang_en_us"`

	// LangEsEs Name of a product in es-ES language
	LangEsEs string `json:"lang_es_es"`

	// Name Name of a product
	Name string      `json:"name"`
	Unit interface{} `json:"unit"`
	Uuid interface{} `json:"uuid"`

	// Vendor Vendor of a product
	Vendor string `json:"vendor"`
}

// Products List of products.
type Products = []Product

// UUID Unique identifier of an item
type UUID = openapi_types.UUID
