package seed

//var (
//	water = &domain.Product{
//		Name:     "water",
//		LangEsES: "Agua",
//		LangEnUS: "Water",
//		Vendor:   biz.VendorGeneric,
//		Unit:     domain.Unit_LITER,
//		NutritionFacts: &domain.NutritionFacts{
//			Cal: domain.Cal(0).Value(),
//		},
//	}
//	coffeeEspresso = &domain.Product{
//		Name:     "coffee espresso",
//		LangEsES: "Cafe espresso",
//		LangEnUS: "Espresso Coffee",
//		Vendor:   biz.VendorGeneric,
//		Unit:     domain.Unit_LITER,
//		NutritionFacts: &domain.NutritionFacts{
//			Cal:               domain.Kcal(9).Value(),
//			FatTotal:          domain.Gram(0.2).Value(),
//			Sodium:            domain.MilliGram(14).Value(),
//			Potassium:         domain.MilliGram(115).Value(),
//			CarbohydrateTotal: domain.Gram(1.7).Value(),
//			Protein:           domain.Gram(0.1).Value(),
//			Caffeine:          domain.MilliGram(212).Value(),
//		},
//	}
//	mincedBeef = &domain.Product{
//		Name:     "minced beef",
//		LangEsES: "Carne picada de vacuno",
//		LangEnUS: "Minced Beef",
//		Vendor:   biz.VendorHacendado,
//		Unit:     domain.Unit_GRAM,
//		NutritionFacts: &domain.NutritionFacts{
//			Cal:               domain.Kcal(204).Value(),
//			FatTotal:          domain.Gram(14).Value(),
//			FatSaturated:      domain.Gram(6.6).Value(),
//			CarbohydrateTotal: domain.Gram(0.5).Value(),
//			CarbohydrateSugar: domain.Gram(0.5).Value(),
//			Protein:           domain.Gram(19).Value(),
//			Salt:              domain.Gram(0.4).Value(),
//		},
//	}
//	bonelessSkinlessChickenThighs = &domain.Product{
//		Name:     "boneless skinless chicken thighs",
//		LangEsES: "Contramuslo de pollo sin piel deshuesado",
//		LangEnUS: "Boneless skinless chicken thighs",
//		Vendor:   biz.VendorHacendado,
//		Unit:     domain.Unit_GRAM,
//		NutritionFacts: &domain.NutritionFacts{
//			Cal:               domain.Kcal(116).Value(),
//			FatTotal:          domain.Gram(1.7).Value(),
//			FatSaturated:      domain.Gram(0.71).Value(),
//			CarbohydrateTotal: domain.Gram(0.4).Value(),
//			CarbohydrateSugar: domain.Gram(0.4).Value(),
//			Protein:           domain.MilliGram(25).Value(),
//			Sodium:            domain.MilliGram(110).Value(),
//		},
//	}
//	potato = &domain.Product{
//		Name:     "potato",
//		LangEsES: "Patata",
//		LangEnUS: "Potato",
//		Vendor:   biz.VendorHacendado,
//		Unit:     domain.Unit_GRAM,
//		NutritionFacts: &domain.NutritionFacts{
//			Cal:               domain.Kcal(68).Value(),
//			CarbohydrateTotal: domain.Gram(14.5).Value(),
//			CarbohydrateSugar: domain.Gram(2.1).Value(),
//			Fiber:             domain.Gram(1.4).Value(),
//			Protein:           domain.Gram(1.9).Value(),
//			Sodium:            domain.MilliGram(10).Value(),
//			VitaminC:          domain.MilliGram(25).Value(),
//		},
//	}
//	mollete = &domain.Product{
//		Name:     "mollete bread",
//		LangEsES: "Mollete de pan",
//		LangEnUS: "Mollete bread",
//		Vendor:   biz.VendorHacendado,
//		Unit:     domain.Unit_GRAM,
//		NutritionFacts: &domain.NutritionFacts{
//			Cal:                domain.Kcal(235).Value(),
//			FatTotal:           domain.Gram(1.1).Value(),
//			FatSaturated:       domain.Gram(0.2).Value(),
//			FatMonounsaturated: domain.Gram(0.3).Value(),
//			FatPolyunsaturated: domain.Gram(0.6).Value(),
//			CarbohydrateTotal:  domain.Gram(46.5).Value(),
//			CarbohydrateSugar:  domain.Gram(1.3).Value(),
//			Fiber:              domain.Gram(2.5).Value(),
//			Protein:            domain.Gram(8.5).Value(),
//			Salt:               domain.Gram(1.29).Value(),
//		},
//	}
//	turkeyBreastSausage92 = &domain.Product{
//		Name:     "turkey breast sausage 92%",
//		LangEsES: "Embutido de pechuga de pavo 92%",
//		LangEnUS: "Turkey breast sausage 92%",
//		Vendor:   biz.VendorHacendado,
//		Unit:     domain.Unit_GRAM,
//		NutritionFacts: &domain.NutritionFacts{
//			Cal:               domain.Kcal(89).Value(),
//			FatTotal:          domain.Gram(1.3).Value(),
//			FatSaturated:      domain.Gram(0.5).Value(),
//			CarbohydrateTotal: domain.Gram(0.9).Value(),
//			CarbohydrateSugar: domain.Gram(0.9).Value(),
//			Protein:           domain.Gram(19.5).Value(),
//			Salt:              domain.Gram(1.9).Value(),
//		},
//	}
//	tortiglioni = &domain.Product{
//		Name:     "tortiglioni",
//		LangEsES: "Tortiglioni",
//		LangEnUS: "Tortiglioni",
//		Vendor:   biz.VendorArmando,
//		Unit:     domain.Unit_GRAM,
//		NutritionFacts: &domain.NutritionFacts{
//			Cal:               domain.Kcal(354).Value(),
//			FatTotal:          domain.Gram(1.3).Value(),
//			FatSaturated:      domain.Gram(0.3).Value(),
//			CarbohydrateTotal: domain.Gram(70.2).Value(),
//			CarbohydrateSugar: domain.Gram(3.2).Value(),
//			Fiber:             domain.Gram(2.7).Value(),
//			Protein:           domain.MilliGram(14).Value(),
//			Salt:              domain.MilliGram(5).Value(),
//		},
//	}
//	porkSteakNoodles = &domain.Product{
//		Name:     "pork steak ramen noodles",
//		LangEsES: "Noodles de trigo especiales para ramen de costillas de cerdo",
//		LangEnUS: "Pork steak ramen noodles",
//		Vendor:   biz.VendorMaiAunt,
//		Unit:     domain.Unit_GRAM,
//		NutritionFacts: &domain.NutritionFacts{
//			Cal:               domain.Kcal(350).Value(),
//			FatTotal:          domain.Gram(0.8).Value(),
//			CarbohydrateTotal: domain.Gram(76.7).Value(),
//			Protein:           domain.Gram(9.3).Value(),
//			Salt:              domain.Gram(1.74).Value(),
//		},
//	}
//	redPepper = &domain.Product{
//		Name:     "red pepper",
//		LangEsES: "Pimiento rojo",
//		LangEnUS: "Red pepper",
//		Vendor:   biz.VendorGeneric,
//		Unit:     domain.Unit_GRAM,
//		NutritionFacts: &domain.NutritionFacts{
//			Cal:                domain.Kcal(26).Value(),
//			Protein:            domain.Gram(0.99).Value(),
//			FatTotal:           domain.Gram(0.3).Value(),
//			FatPolyunsaturated: domain.Gram(0.156).Value(),
//			FatSaturated:       domain.Gram(0.059).Value(),
//			FatMonounsaturated: domain.Gram(0.007).Value(),
//			CarbohydrateTotal:  domain.Gram(6.03).Value(),
//			CarbohydrateSugar:  domain.Gram(4.2).Value(),
//			Fiber:              domain.Gram(2).Value(),
//			Sodium:             domain.MilliGram(2).Value(),
//			Potassium:          domain.MilliGram(211).Value(),
//		},
//	}
//	greenPepper = &domain.Product{
//		Name:     "green pepper",
//		LangEsES: "Pimiento verde",
//		LangEnUS: "Green pepper",
//		Vendor:   biz.VendorGeneric,
//		Unit:     domain.Unit_GRAM,
//		NutritionFacts: &domain.NutritionFacts{
//			Cal:                domain.Kcal(20).Value(),
//			Protein:            domain.Gram(0.86).Value(),
//			FatTotal:           domain.Gram(0.170).Value(),
//			FatPolyunsaturated: domain.Gram(0.062).Value(),
//			FatSaturated:       domain.Gram(0.058).Value(),
//			FatMonounsaturated: domain.Gram(0.008).Value(),
//			Fiber:              domain.Gram(1.7).Value(),
//			CarbohydrateTotal:  domain.Gram(4.64).Value(),
//			CarbohydrateSugar:  domain.Gram(2.4).Value(),
//			Sodium:             domain.MilliGram(3).Value(),
//			Potassium:          domain.MilliGram(175).Value(),
//		},
//	}
//	sweetOnion = &domain.Product{
//		Name:     "sweet onion",
//		LangEsES: "Cebolla dulce",
//		LangEnUS: "Sweet onion",
//		Vendor:   biz.VendorGeneric,
//		Unit:     domain.Unit_GRAM,
//		NutritionFacts: &domain.NutritionFacts{
//			Cal:               domain.Kcal(32).Value(),
//			Protein:           domain.Gram(0.08).Value(),
//			FatTotal:          domain.Gram(0.08).Value(),
//			CarbohydrateTotal: domain.Gram(7.55).Value(),
//			CarbohydrateSugar: domain.Gram(5.02).Value(),
//			Fiber:             domain.Gram(0.9).Value(),
//			Sodium:            domain.MilliGram(8).Value(),
//		},
//	}
//	onion = &domain.Product{
//		Name:     "onion",
//		LangEsES: "Cebolla blanca",
//		LangEnUS: "White onion",
//		Vendor:   biz.VendorGeneric,
//		Unit:     domain.Unit_GRAM,
//		NutritionFacts: &domain.NutritionFacts{
//			Cal:                domain.Kcal(42).Value(),
//			Protein:            domain.Gram(0.92).Value(),
//			FatTotal:           domain.Gram(0.08).Value(),
//			FatMonounsaturated: domain.Gram(0.023).Value(),
//			FatPolyunsaturated: domain.Gram(0.062).Value(),
//			FatSaturated:       domain.Gram(0.026).Value(),
//			CarbohydrateTotal:  domain.Gram(10.11).Value(),
//			CarbohydrateSugar:  domain.Gram(4.28).Value(),
//			Fiber:              domain.Gram(1.4).Value(),
//			Sodium:             domain.MilliGram(3).Value(),
//			Potassium:          domain.MilliGram(144).Value(),
//		},
//	}
//	tomato = &domain.Product{
//		Name:     "tomato",
//		LangEsES: "Tomate",
//		LangEnUS: "Tomato",
//		Vendor:   biz.VendorGeneric,
//		Unit:     domain.Unit_GRAM,
//		NutritionFacts: &domain.NutritionFacts{
//			Cal:                domain.Kcal(22).Value(),
//			FatTotal:           domain.Gram(0.25).Value(),
//			FatSaturated:       domain.Gram(0.057).Value(),
//			FatPolyunsaturated: domain.Gram(0.166).Value(),
//			FatMonounsaturated: domain.Gram(0.063).Value(),
//			CarbohydrateTotal:  domain.Gram(4.82).Value(),
//			Fiber:              domain.Gram(1.5).Value(),
//			CarbohydrateSugar:  domain.Gram(3.23).Value(),
//			Sodium:             domain.MilliGram(6).Value(),
//			Potassium:          domain.MilliGram(292).Value(),
//			Protein:            domain.Gram(1.08).Value(),
//		},
//	}
//	japaneseMayo = &domain.Product{
//		Name:     "Japanese Mayo",
//		LangEsES: "Mayonesa Japonesa",
//		LangEnUS: "Japanese Mayo",
//		Vendor:   biz.VendorKewpie,
//		Unit:     domain.Unit_GRAM,
//		NutritionFacts: &domain.NutritionFacts{
//			Cal:               domain.Kcal(694).Value(),
//			FatTotal:          domain.Gram(74).Value(),
//			FatSaturated:      domain.Gram(6.6).Value(),
//			CarbohydrateTotal: domain.Gram(4.1).Value(),
//			CarbohydrateSugar: domain.Gram(1.8).Value(),
//			Protein:           domain.Gram(1.9).Value(),
//			Salt:              domain.Gram(2.5).Value(),
//		},
//	}
//	lightMayo = &domain.Product{
//		Name:     "Light Mayo",
//		LangEsES: "Mayonesa Ligera",
//		LangEnUS: "Light Mayo",
//		Vendor:   biz.VendorHacendado,
//		Unit:     domain.Unit_GRAM,
//		NutritionFacts: &domain.NutritionFacts{
//			Cal:               domain.Kcal(294).Value(),
//			FatTotal:          domain.Gram(31).Value(),
//			FatSaturated:      domain.Gram(4.8).Value(),
//			CarbohydrateTotal: domain.Gram(6.5).Value(),
//			CarbohydrateSugar: domain.Gram(3.5).Value(),
//			Protein:           domain.Gram(0.7).Value(),
//			Salt:              domain.Gram(2.1).Value(),
//		},
//	}
//	mayo = &domain.Product{
//		Name:     "Mayo",
//		LangEsES: "Mayonesa",
//		LangEnUS: "Mayo",
//		Vendor:   biz.VendorHacendado,
//		Unit:     domain.Unit_GRAM,
//		NutritionFacts: &domain.NutritionFacts{
//			Cal:               domain.Kcal(599).Value(),
//			FatTotal:          domain.Gram(65).Value(),
//			FatSaturated:      domain.Gram(9.7).Value(),
//			CarbohydrateTotal: domain.Gram(2.4).Value(),
//			CarbohydrateSugar: domain.Gram(1.33).Value(),
//			Protein:           domain.Gram(0.6).Value(),
//			Salt:              domain.Gram(1.1).Value(),
//		},
//	}
//	duckThighConfit = &domain.Product{
//		Name:     "duck thigh confit",
//		LangEsES: "Muslo de pato confitado",
//		LangEnUS: "Duck thigh confit",
//		Vendor:   biz.VendorHacendado,
//		Unit:     domain.Unit_GRAM,
//		NutritionFacts: &domain.NutritionFacts{
//			Cal:               domain.Kcal(269).Value(),
//			FatTotal:          domain.Gram(19).Value(),
//			FatSaturated:      domain.Gram(5.9).Value(),
//			CarbohydrateTotal: domain.Gram(1.1).Value(),
//			CarbohydrateSugar: domain.Gram(1.1).Value(),
//			Protein:           domain.Gram(23).Value(),
//			Salt:              domain.Gram(1.5).Value(),
//		},
//	}
//	zucchini = &domain.Product{
//		Name:     "zucchini",
//		LangEsES: "Calabacín",
//		LangEnUS: "Zucchini",
//		Vendor:   biz.VendorGeneric,
//		Unit:     domain.Unit_GRAM,
//		NutritionFacts: &domain.NutritionFacts{
//			Cal:                domain.Kcal(16).Value(),
//			FatTotal:           domain.MilliGram(180).Value(),
//			FatSaturated:       domain.MilliGram(37).Value(),
//			FatMonounsaturated: domain.MilliGram(14).Value(),
//			FatPolyunsaturated: domain.MilliGram(76).Value(),
//			Salt:               domain.MilliGram(20).Value(),
//			Potassium:          domain.MilliGram(262).Value(),
//			CarbohydrateTotal:  domain.Gram(3.35).Value(),
//			CarbohydrateSugar:  domain.Gram(1.73).Value(),
//			Protein:            domain.Gram(1.21).Value(),
//			Fiber:              domain.Gram(1.1).Value(),
//			Calcium:            domain.MilliGram(15).Value(),
//			Iron:               domain.MilliGram(0.35).Value(),
//			VitaminA:           domain.MicroGram(10).Value(),
//			VitaminC:           domain.MicroGram(17).Value(),
//		},
//	}
//	pepperOnionAndZucchiniMix = &domain.Product{
//		Name:     "pepper onion and zucchini",
//		LangEsES: "Preparado de pimiento, cebolla y calabacín",
//		LangEnUS: "Pepper, onion and zucchini mix",
//		Vendor:   biz.VendorHacendado,
//		Unit:     domain.Unit_GRAM,
//		NutritionFacts: &domain.NutritionFacts{
//			Cal:               domain.Kcal(30).Value(),
//			FatTotal:          domain.MilliGram(200).Value(),
//			FatSaturated:      domain.MilliGram(100).Value(),
//			Salt:              domain.MilliGram(10).Value(),
//			CarbohydrateTotal: domain.Gram(5.2).Value(),
//			CarbohydrateSugar: domain.Gram(3.1).Value(),
//			Protein:           domain.Gram(1.1).Value(),
//			Fiber:             domain.Gram(1.4).Value(),
//		},
//	}
//
//	products = []*domain.Product{
//		bonelessSkinlessChickenThighs,
//		coffeeEspresso,
//		duckThighConfit,
//		extraVirginOliveOil,
//		greenPepper,
//		japaneseMayo,
//		lightMayo,
//		mayo,
//		mincedBeef,
//		mollete,
//		onion,
//		pepperOnionAndZucchiniMix,
//		porkSteakNoodles,
//		potato,
//		redPepper,
//		semiSkimmedMilk,
//		sweetOnion,
//		tomato,
//		tortiglioni,
//		turkeyBreastSausage92,
//		water,
//		zucchini,
//	}
//)
