// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for Gender.
const (
	Female Gender = "female"
	Male   Gender = "male"
)

// Defines values for MenuLabel.
const (
	AFTERNOONSNACK MenuLabel = "AFTERNOON_SNACK"
	BREAKFAST      MenuLabel = "BREAKFAST"
	DINNER         MenuLabel = "DINNER"
	LUNCH          MenuLabel = "LUNCH"
	MORNINGSNACK   MenuLabel = "MORNING_SNACK"
)

// Defines values for Unit.
const (
	G Unit = "g"
	L Unit = "l"
)

// ConstraintsViolation It represents a constraints violation error
type ConstraintsViolation struct {
	// Field The field that is causing the constraints violation
	Field string `json:"field"`

	// Message The human-readable constraints violation description
	Message string `json:"message"`
}

// ConstraintsViolationsError Note: It follows [RFC-7807](https://tools.ietf.org/html/rfc7807#page-9) **proposed** standard
//
// Error object returned on any failure. It can be extended to add more params
type ConstraintsViolationsError = Error

// DailyMenu A daily menu
type DailyMenu struct {
	// Name Name of a daily menu
	Name string      `json:"name"`
	Uuid interface{} `json:"uuid"`
}

// DailyMenuDetailed An ingredient
type DailyMenuDetailed struct {
	Menus interface{} `json:"menus"`

	// Name Name of a daily menu
	Name                string       `json:"name"`
	NutritionFactsTotal *interface{} `json:"nutrition_facts_total,omitempty"`
	Uuid                interface{}  `json:"uuid"`
}

// DailyMenus List of daily menus.
type DailyMenus = []DailyMenu

// DailyMenusDetailed List of daily menus.
type DailyMenusDetailed = []DailyMenuDetailed

// DailyValues Recommended Daily Values
type DailyValues struct {
	// Caffeine Caffeine DV (%)
	Caffeine *float32 `json:"caffeine,omitempty"`

	// Calcium Calcium DV (%)
	Calcium *float32 `json:"calcium,omitempty"`

	// CarbohydrateSugar Sugar Carbohydrates DV (%)
	CarbohydrateSugar *float32 `json:"carbohydrate_sugar,omitempty"`

	// CarbohydrateTotal Total Carbohydrates DV (%)
	CarbohydrateTotal *float32 `json:"carbohydrate_total,omitempty"`

	// Cholesterol Cholesterol DV (%)
	Cholesterol *float32 `json:"cholesterol,omitempty"`

	// FatSaturated Saturated fats DV (%)
	FatSaturated *float32 `json:"fat_saturated,omitempty"`

	// Fiber Fiber DV (%)
	Fiber *float32 `json:"fiber,omitempty"`

	// Iron Iron DV (%)
	Iron *float32 `json:"iron,omitempty"`

	// Potassium Potassium DV (%)
	Potassium *float32 `json:"potassium,omitempty"`

	// Protein Proteins DV (%)
	Protein *float32 `json:"protein,omitempty"`

	// Salt Salt DV (%)
	Salt *float32 `json:"salt,omitempty"`

	// Sodium Sodium DV (%)
	Sodium *float32 `json:"sodium,omitempty"`

	// VitaminA Vitamin A DV (%)
	VitaminA *float32 `json:"vitamin_a,omitempty"`

	// VitaminB1 Vitamin B1 DV (%)
	VitaminB1 *float32 `json:"vitamin_b1,omitempty"`

	// VitaminB12 Vitamin B12 DV (%)
	VitaminB12 *float32 `json:"vitamin_b12,omitempty"`

	// VitaminB2 Vitamin B2 DV (%)
	VitaminB2 *float32 `json:"vitamin_b2,omitempty"`

	// VitaminB3 Vitamin B3 DV (%)
	VitaminB3 *float32 `json:"vitamin_b3,omitempty"`

	// VitaminB4 Vitamin B4 DV (%)
	VitaminB4 *float32 `json:"vitamin_b4,omitempty"`

	// VitaminB5 Vitamin B5 DV (%)
	VitaminB5 *float32 `json:"vitamin_b5,omitempty"`

	// VitaminB6 Vitamin B6 DV (%)
	VitaminB6 *float32 `json:"vitamin_b6,omitempty"`

	// VitaminC Vitamin C DV (%)
	VitaminC *float32 `json:"vitamin_c,omitempty"`

	// VitaminD Vitamin D DV (%)
	VitaminD *float32 `json:"vitamin_d,omitempty"`

	// VitaminE Vitamin E DV (%)
	VitaminE *float32 `json:"vitamin_e,omitempty"`

	// VitaminK Vitamin K DV (%)
	VitaminK *float32 `json:"vitamin_k,omitempty"`
}

// Error Note: It follows [RFC-7807](https://tools.ietf.org/html/rfc7807#page-9) **proposed** standard
//
// Error object returned on any failure. It can be extended to add more params
type Error struct {
	// Detail A human-readable explanation specific to this occurrence of the problem
	Detail *string `json:"detail,omitempty"`

	// Status The HTTP status code generated by the origin server for this occurrence of the problem
	Status int `json:"status"`

	// Title A short, human-readable summary of the problem type
	Title string `json:"title"`
}

// Gender User gender.
type Gender string

// Ingredient An ingredient
type Ingredient struct {
	Product interface{} `json:"product"`

	// Quantity Product quantity
	Quantity float32 `json:"quantity"`
}

// IngredientDetailed An ingredient
type IngredientDetailed struct {
	Product interface{} `json:"product"`

	// Quantity Product quantity
	Quantity float32 `json:"quantity"`
}

// Ingredients List of ingredients.
type Ingredients = []Ingredient

// IngredientsDetailed List of ingredients.
type IngredientsDetailed = []IngredientDetailed

// Menu A menu
type Menu struct {
	Label interface{} `json:"label"`

	// Name Name of a menu
	Name string      `json:"name"`
	Uuid interface{} `json:"uuid"`
}

// MenuDetailed An ingredient
type MenuDetailed struct {
	Ingredients *interface{} `json:"ingredients,omitempty"`
	Label       interface{}  `json:"label"`

	// Name Name of a menu
	Name                string       `json:"name"`
	NutritionFactsTotal *interface{} `json:"nutrition_facts_total,omitempty"`
	Recipes             *interface{} `json:"recipes,omitempty"`
	Uuid                interface{}  `json:"uuid"`
}

// MenuLabel Menu label.
type MenuLabel string

// Menus List of menus.
type Menus = []Menu

// MenusDetailed List of menus.
type MenusDetailed = []MenuDetailed

// NutritionFacts Nutrition facts of a meal
type NutritionFacts struct {
	// Caffeine Caffeine (g)
	Caffeine *float32 `json:"caffeine,omitempty"`

	// Cal Calories (cal)
	Cal float32 `json:"cal"`

	// Calcium Calcium (g)
	Calcium *float32 `json:"calcium,omitempty"`

	// CarbohydrateSugar Sugar Carbohydrates (g)
	CarbohydrateSugar *float32 `json:"carbohydrate_sugar,omitempty"`

	// CarbohydrateTotal Total Carbohydrates (g)
	CarbohydrateTotal *float32 `json:"carbohydrate_total,omitempty"`

	// Cholesterol Cholesterol (g)
	Cholesterol *float32 `json:"cholesterol,omitempty"`

	// FatMonounsaturated Monounsaturated fats (g)
	FatMonounsaturated *float32 `json:"fat_monounsaturated,omitempty"`

	// FatPolyunsaturated Polyunsaturated fats (g)
	FatPolyunsaturated *float32 `json:"fat_polyunsaturated,omitempty"`

	// FatSaturated Saturated fats (g)
	FatSaturated *float32 `json:"fat_saturated,omitempty"`

	// FatTotal Total fats (g)
	FatTotal *float32 `json:"fat_total,omitempty"`

	// Fiber Fiber (g)
	Fiber *float32 `json:"fiber,omitempty"`

	// Iron Iron (g)
	Iron *float32 `json:"iron,omitempty"`

	// Potassium Potassium (g)
	Potassium *float32 `json:"potassium,omitempty"`

	// Protein Proteins (g)
	Protein *float32 `json:"protein,omitempty"`

	// Salt Salt (g)
	Salt *float32 `json:"salt,omitempty"`

	// Sodium Sodium (g)
	Sodium *float32 `json:"sodium,omitempty"`

	// VitaminA Vitamin A (g)
	VitaminA *float32 `json:"vitamin_a,omitempty"`

	// VitaminB1 Vitamin B1 (g)
	VitaminB1 *float32 `json:"vitamin_b1,omitempty"`

	// VitaminB12 Vitamin B12 (g)
	VitaminB12 *float32 `json:"vitamin_b12,omitempty"`

	// VitaminB2 Vitamin B2 (g)
	VitaminB2 *float32 `json:"vitamin_b2,omitempty"`

	// VitaminB3 Vitamin B3 (g)
	VitaminB3 *float32 `json:"vitamin_b3,omitempty"`

	// VitaminB4 Vitamin B4 (g)
	VitaminB4 *float32 `json:"vitamin_b4,omitempty"`

	// VitaminB5 Vitamin B5 (g)
	VitaminB5 *float32 `json:"vitamin_b5,omitempty"`

	// VitaminB6 Vitamin B6 (g)
	VitaminB6 *float32 `json:"vitamin_b6,omitempty"`

	// VitaminC Vitamin C (g)
	VitaminC *float32 `json:"vitamin_c,omitempty"`

	// VitaminD Vitamin D (g)
	VitaminD *float32 `json:"vitamin_d,omitempty"`

	// VitaminE Vitamin E (g)
	VitaminE *float32 `json:"vitamin_e,omitempty"`

	// VitaminK Vitamin K (g)
	VitaminK *float32 `json:"vitamin_k,omitempty"`
}

// Product A product
type Product struct {
	// LangEnUs Name of a product in en-US language
	LangEnUs string `json:"lang_en_us"`

	// LangEsEs Name of a product in es-ES language
	LangEsEs string `json:"lang_es_es"`

	// Name Name of a product
	Name string       `json:"name"`
	Unit interface{}  `json:"unit"`
	Uuid *interface{} `json:"uuid,omitempty"`

	// Vendor Vendor of a product
	Vendor string `json:"vendor"`
}

// ProductDetailed A product
type ProductDetailed struct {
	// LangEnUs Name of a product in en-US language
	LangEnUs string `json:"lang_en_us"`

	// LangEsEs Name of a product in es-ES language
	LangEsEs string `json:"lang_es_es"`

	// Name Name of a product
	Name              string       `json:"name"`
	NutritionFacts100 *interface{} `json:"nutrition_facts_100,omitempty"`
	Unit              interface{}  `json:"unit"`
	Uuid              *interface{} `json:"uuid,omitempty"`

	// Vendor Vendor of a product
	Vendor string `json:"vendor"`
}

// Products List of products.
type Products = []Product

// Recipe A recipe
type Recipe struct {
	// Name Name of a recipe
	Name string       `json:"name"`
	Uuid *interface{} `json:"uuid,omitempty"`
}

// RecipeDetailed A recipe
type RecipeDetailed struct {
	Ingredients interface{} `json:"ingredients"`

	// Name Name of a recipe
	Name                string       `json:"name"`
	NutritionFacts100   *interface{} `json:"nutrition_facts_100,omitempty"`
	NutritionFactsTotal *interface{} `json:"nutrition_facts_total,omitempty"`

	// Quantity Total quantity
	Quantity *float32     `json:"quantity,omitempty"`
	Uuid     *interface{} `json:"uuid,omitempty"`
}

// Recipes List of recipes.
type Recipes = []Recipe

// RecipesDetailed List of recipes.
type RecipesDetailed = []RecipeDetailed

// Unit Measure unit.
type Unit string

// User A user
type User struct {
	// Birthday Birthday of a user
	Birthday openapi_types.Date `json:"birthday"`

	// BmrMifflinStJeor Basal Metabolism Rate according to the Mifflin-St Jeor equation
	BmrMifflinStJeor *float32 `json:"bmr_mifflin_st_jeor,omitempty"`

	// BmrRevisedHarrisBenedict Basal Metabolism Rate according to the revised Harris Benedict equation
	BmrRevisedHarrisBenedict *float32 `json:"bmr_revised_harris_benedict,omitempty"`

	// Email Email of a user
	Email string `json:"email"`

	// Gender Email of a user
	Gender string `json:"gender"`

	// Height Height of a user
	Height float32 `json:"height"`

	// Name Name of a user
	Name string       `json:"name"`
	Uuid *interface{} `json:"uuid,omitempty"`

	// Weight Weight of a user
	Weight float32 `json:"weight"`
}

// Users List of users.
type Users = []User

// DailyMenuID defines model for DailyMenuID.
type DailyMenuID = openapi_types.UUID

// MenuID defines model for MenuID.
type MenuID = openapi_types.UUID

// ProductID defines model for ProductID.
type ProductID = openapi_types.UUID

// RecipeID defines model for RecipeID.
type RecipeID = openapi_types.UUID

// UserID defines model for UserID.
type UserID = openapi_types.UUID

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetAdminUsers request
	GetAdminUsers(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetProducts request
	GetProducts(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetProductsProductId request
	GetProductsProductId(ctx context.Context, productId ProductID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetProductsProductIdNutritionFacts request
	GetProductsProductIdNutritionFacts(ctx context.Context, productId ProductID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUsersUserId request
	GetUsersUserId(ctx context.Context, userId UserID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUsersUserIdDailyMenus request
	GetUsersUserIdDailyMenus(ctx context.Context, userId UserID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUsersUserIdDailyMenusDailyMenuId request
	GetUsersUserIdDailyMenusDailyMenuId(ctx context.Context, userId UserID, dailyMenuId DailyMenuID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUsersUserIdMenus request
	GetUsersUserIdMenus(ctx context.Context, userId UserID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUsersUserIdMenusMenuId request
	GetUsersUserIdMenusMenuId(ctx context.Context, userId UserID, menuId MenuID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUsersUserIdRecipes request
	GetUsersUserIdRecipes(ctx context.Context, userId UserID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUsersUserIdRecipesRecipeId request
	GetUsersUserIdRecipesRecipeId(ctx context.Context, userId UserID, recipeId RecipeID, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetAdminUsers(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAdminUsersRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetProducts(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetProductsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetProductsProductId(ctx context.Context, productId ProductID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetProductsProductIdRequest(c.Server, productId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetProductsProductIdNutritionFacts(ctx context.Context, productId ProductID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetProductsProductIdNutritionFactsRequest(c.Server, productId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetUsersUserId(ctx context.Context, userId UserID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUsersUserIdRequest(c.Server, userId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetUsersUserIdDailyMenus(ctx context.Context, userId UserID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUsersUserIdDailyMenusRequest(c.Server, userId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetUsersUserIdDailyMenusDailyMenuId(ctx context.Context, userId UserID, dailyMenuId DailyMenuID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUsersUserIdDailyMenusDailyMenuIdRequest(c.Server, userId, dailyMenuId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetUsersUserIdMenus(ctx context.Context, userId UserID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUsersUserIdMenusRequest(c.Server, userId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetUsersUserIdMenusMenuId(ctx context.Context, userId UserID, menuId MenuID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUsersUserIdMenusMenuIdRequest(c.Server, userId, menuId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetUsersUserIdRecipes(ctx context.Context, userId UserID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUsersUserIdRecipesRequest(c.Server, userId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetUsersUserIdRecipesRecipeId(ctx context.Context, userId UserID, recipeId RecipeID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUsersUserIdRecipesRecipeIdRequest(c.Server, userId, recipeId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetAdminUsersRequest generates requests for GetAdminUsers
func NewGetAdminUsersRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/users")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetProductsRequest generates requests for GetProducts
func NewGetProductsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/products")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetProductsProductIdRequest generates requests for GetProductsProductId
func NewGetProductsProductIdRequest(server string, productId ProductID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "product_id", runtime.ParamLocationPath, productId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/products/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetProductsProductIdNutritionFactsRequest generates requests for GetProductsProductIdNutritionFacts
func NewGetProductsProductIdNutritionFactsRequest(server string, productId ProductID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "product_id", runtime.ParamLocationPath, productId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/products/%s/nutrition-facts", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetUsersUserIdRequest generates requests for GetUsersUserId
func NewGetUsersUserIdRequest(server string, userId UserID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "user_id", runtime.ParamLocationPath, userId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/users/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetUsersUserIdDailyMenusRequest generates requests for GetUsersUserIdDailyMenus
func NewGetUsersUserIdDailyMenusRequest(server string, userId UserID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "user_id", runtime.ParamLocationPath, userId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/users/%s/daily-menus", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetUsersUserIdDailyMenusDailyMenuIdRequest generates requests for GetUsersUserIdDailyMenusDailyMenuId
func NewGetUsersUserIdDailyMenusDailyMenuIdRequest(server string, userId UserID, dailyMenuId DailyMenuID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "user_id", runtime.ParamLocationPath, userId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "daily_menu_id", runtime.ParamLocationPath, dailyMenuId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/users/%s/daily-menus/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetUsersUserIdMenusRequest generates requests for GetUsersUserIdMenus
func NewGetUsersUserIdMenusRequest(server string, userId UserID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "user_id", runtime.ParamLocationPath, userId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/users/%s/menus", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetUsersUserIdMenusMenuIdRequest generates requests for GetUsersUserIdMenusMenuId
func NewGetUsersUserIdMenusMenuIdRequest(server string, userId UserID, menuId MenuID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "user_id", runtime.ParamLocationPath, userId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "menu_id", runtime.ParamLocationPath, menuId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/users/%s/menus/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetUsersUserIdRecipesRequest generates requests for GetUsersUserIdRecipes
func NewGetUsersUserIdRecipesRequest(server string, userId UserID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "user_id", runtime.ParamLocationPath, userId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/users/%s/recipes", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetUsersUserIdRecipesRecipeIdRequest generates requests for GetUsersUserIdRecipesRecipeId
func NewGetUsersUserIdRecipesRecipeIdRequest(server string, userId UserID, recipeId RecipeID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "user_id", runtime.ParamLocationPath, userId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "recipe_id", runtime.ParamLocationPath, recipeId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/users/%s/recipes/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetAdminUsersWithResponse request
	GetAdminUsersWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAdminUsersResponse, error)

	// GetProductsWithResponse request
	GetProductsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetProductsResponse, error)

	// GetProductsProductIdWithResponse request
	GetProductsProductIdWithResponse(ctx context.Context, productId ProductID, reqEditors ...RequestEditorFn) (*GetProductsProductIdResponse, error)

	// GetProductsProductIdNutritionFactsWithResponse request
	GetProductsProductIdNutritionFactsWithResponse(ctx context.Context, productId ProductID, reqEditors ...RequestEditorFn) (*GetProductsProductIdNutritionFactsResponse, error)

	// GetUsersUserIdWithResponse request
	GetUsersUserIdWithResponse(ctx context.Context, userId UserID, reqEditors ...RequestEditorFn) (*GetUsersUserIdResponse, error)

	// GetUsersUserIdDailyMenusWithResponse request
	GetUsersUserIdDailyMenusWithResponse(ctx context.Context, userId UserID, reqEditors ...RequestEditorFn) (*GetUsersUserIdDailyMenusResponse, error)

	// GetUsersUserIdDailyMenusDailyMenuIdWithResponse request
	GetUsersUserIdDailyMenusDailyMenuIdWithResponse(ctx context.Context, userId UserID, dailyMenuId DailyMenuID, reqEditors ...RequestEditorFn) (*GetUsersUserIdDailyMenusDailyMenuIdResponse, error)

	// GetUsersUserIdMenusWithResponse request
	GetUsersUserIdMenusWithResponse(ctx context.Context, userId UserID, reqEditors ...RequestEditorFn) (*GetUsersUserIdMenusResponse, error)

	// GetUsersUserIdMenusMenuIdWithResponse request
	GetUsersUserIdMenusMenuIdWithResponse(ctx context.Context, userId UserID, menuId MenuID, reqEditors ...RequestEditorFn) (*GetUsersUserIdMenusMenuIdResponse, error)

	// GetUsersUserIdRecipesWithResponse request
	GetUsersUserIdRecipesWithResponse(ctx context.Context, userId UserID, reqEditors ...RequestEditorFn) (*GetUsersUserIdRecipesResponse, error)

	// GetUsersUserIdRecipesRecipeIdWithResponse request
	GetUsersUserIdRecipesRecipeIdWithResponse(ctx context.Context, userId UserID, recipeId RecipeID, reqEditors ...RequestEditorFn) (*GetUsersUserIdRecipesRecipeIdResponse, error)
}

type GetAdminUsersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Users
	JSON400      *ConstraintsViolationsError
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GetAdminUsersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAdminUsersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetProductsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Products
	JSON400      *ConstraintsViolationsError
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GetProductsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetProductsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetProductsProductIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ProductDetailed
	JSON400      *ConstraintsViolationsError
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GetProductsProductIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetProductsProductIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetProductsProductIdNutritionFactsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *NutritionFacts
	JSON400      *ConstraintsViolationsError
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GetProductsProductIdNutritionFactsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetProductsProductIdNutritionFactsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetUsersUserIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ProductDetailed
	JSON400      *ConstraintsViolationsError
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GetUsersUserIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUsersUserIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetUsersUserIdDailyMenusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DailyMenus
	JSON400      *ConstraintsViolationsError
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GetUsersUserIdDailyMenusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUsersUserIdDailyMenusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetUsersUserIdDailyMenusDailyMenuIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DailyMenuDetailed
	JSON400      *ConstraintsViolationsError
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GetUsersUserIdDailyMenusDailyMenuIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUsersUserIdDailyMenusDailyMenuIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetUsersUserIdMenusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Menus
	JSON400      *ConstraintsViolationsError
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GetUsersUserIdMenusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUsersUserIdMenusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetUsersUserIdMenusMenuIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MenuDetailed
	JSON400      *ConstraintsViolationsError
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GetUsersUserIdMenusMenuIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUsersUserIdMenusMenuIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetUsersUserIdRecipesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Recipes
	JSON400      *ConstraintsViolationsError
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GetUsersUserIdRecipesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUsersUserIdRecipesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetUsersUserIdRecipesRecipeIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RecipeDetailed
	JSON400      *ConstraintsViolationsError
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GetUsersUserIdRecipesRecipeIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUsersUserIdRecipesRecipeIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetAdminUsersWithResponse request returning *GetAdminUsersResponse
func (c *ClientWithResponses) GetAdminUsersWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAdminUsersResponse, error) {
	rsp, err := c.GetAdminUsers(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAdminUsersResponse(rsp)
}

// GetProductsWithResponse request returning *GetProductsResponse
func (c *ClientWithResponses) GetProductsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetProductsResponse, error) {
	rsp, err := c.GetProducts(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetProductsResponse(rsp)
}

// GetProductsProductIdWithResponse request returning *GetProductsProductIdResponse
func (c *ClientWithResponses) GetProductsProductIdWithResponse(ctx context.Context, productId ProductID, reqEditors ...RequestEditorFn) (*GetProductsProductIdResponse, error) {
	rsp, err := c.GetProductsProductId(ctx, productId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetProductsProductIdResponse(rsp)
}

// GetProductsProductIdNutritionFactsWithResponse request returning *GetProductsProductIdNutritionFactsResponse
func (c *ClientWithResponses) GetProductsProductIdNutritionFactsWithResponse(ctx context.Context, productId ProductID, reqEditors ...RequestEditorFn) (*GetProductsProductIdNutritionFactsResponse, error) {
	rsp, err := c.GetProductsProductIdNutritionFacts(ctx, productId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetProductsProductIdNutritionFactsResponse(rsp)
}

// GetUsersUserIdWithResponse request returning *GetUsersUserIdResponse
func (c *ClientWithResponses) GetUsersUserIdWithResponse(ctx context.Context, userId UserID, reqEditors ...RequestEditorFn) (*GetUsersUserIdResponse, error) {
	rsp, err := c.GetUsersUserId(ctx, userId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUsersUserIdResponse(rsp)
}

// GetUsersUserIdDailyMenusWithResponse request returning *GetUsersUserIdDailyMenusResponse
func (c *ClientWithResponses) GetUsersUserIdDailyMenusWithResponse(ctx context.Context, userId UserID, reqEditors ...RequestEditorFn) (*GetUsersUserIdDailyMenusResponse, error) {
	rsp, err := c.GetUsersUserIdDailyMenus(ctx, userId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUsersUserIdDailyMenusResponse(rsp)
}

// GetUsersUserIdDailyMenusDailyMenuIdWithResponse request returning *GetUsersUserIdDailyMenusDailyMenuIdResponse
func (c *ClientWithResponses) GetUsersUserIdDailyMenusDailyMenuIdWithResponse(ctx context.Context, userId UserID, dailyMenuId DailyMenuID, reqEditors ...RequestEditorFn) (*GetUsersUserIdDailyMenusDailyMenuIdResponse, error) {
	rsp, err := c.GetUsersUserIdDailyMenusDailyMenuId(ctx, userId, dailyMenuId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUsersUserIdDailyMenusDailyMenuIdResponse(rsp)
}

// GetUsersUserIdMenusWithResponse request returning *GetUsersUserIdMenusResponse
func (c *ClientWithResponses) GetUsersUserIdMenusWithResponse(ctx context.Context, userId UserID, reqEditors ...RequestEditorFn) (*GetUsersUserIdMenusResponse, error) {
	rsp, err := c.GetUsersUserIdMenus(ctx, userId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUsersUserIdMenusResponse(rsp)
}

// GetUsersUserIdMenusMenuIdWithResponse request returning *GetUsersUserIdMenusMenuIdResponse
func (c *ClientWithResponses) GetUsersUserIdMenusMenuIdWithResponse(ctx context.Context, userId UserID, menuId MenuID, reqEditors ...RequestEditorFn) (*GetUsersUserIdMenusMenuIdResponse, error) {
	rsp, err := c.GetUsersUserIdMenusMenuId(ctx, userId, menuId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUsersUserIdMenusMenuIdResponse(rsp)
}

// GetUsersUserIdRecipesWithResponse request returning *GetUsersUserIdRecipesResponse
func (c *ClientWithResponses) GetUsersUserIdRecipesWithResponse(ctx context.Context, userId UserID, reqEditors ...RequestEditorFn) (*GetUsersUserIdRecipesResponse, error) {
	rsp, err := c.GetUsersUserIdRecipes(ctx, userId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUsersUserIdRecipesResponse(rsp)
}

// GetUsersUserIdRecipesRecipeIdWithResponse request returning *GetUsersUserIdRecipesRecipeIdResponse
func (c *ClientWithResponses) GetUsersUserIdRecipesRecipeIdWithResponse(ctx context.Context, userId UserID, recipeId RecipeID, reqEditors ...RequestEditorFn) (*GetUsersUserIdRecipesRecipeIdResponse, error) {
	rsp, err := c.GetUsersUserIdRecipesRecipeId(ctx, userId, recipeId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUsersUserIdRecipesRecipeIdResponse(rsp)
}

// ParseGetAdminUsersResponse parses an HTTP response from a GetAdminUsersWithResponse call
func ParseGetAdminUsersResponse(rsp *http.Response) (*GetAdminUsersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAdminUsersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Users
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ConstraintsViolationsError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetProductsResponse parses an HTTP response from a GetProductsWithResponse call
func ParseGetProductsResponse(rsp *http.Response) (*GetProductsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetProductsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Products
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ConstraintsViolationsError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetProductsProductIdResponse parses an HTTP response from a GetProductsProductIdWithResponse call
func ParseGetProductsProductIdResponse(rsp *http.Response) (*GetProductsProductIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetProductsProductIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ProductDetailed
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ConstraintsViolationsError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetProductsProductIdNutritionFactsResponse parses an HTTP response from a GetProductsProductIdNutritionFactsWithResponse call
func ParseGetProductsProductIdNutritionFactsResponse(rsp *http.Response) (*GetProductsProductIdNutritionFactsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetProductsProductIdNutritionFactsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest NutritionFacts
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ConstraintsViolationsError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetUsersUserIdResponse parses an HTTP response from a GetUsersUserIdWithResponse call
func ParseGetUsersUserIdResponse(rsp *http.Response) (*GetUsersUserIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUsersUserIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ProductDetailed
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ConstraintsViolationsError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetUsersUserIdDailyMenusResponse parses an HTTP response from a GetUsersUserIdDailyMenusWithResponse call
func ParseGetUsersUserIdDailyMenusResponse(rsp *http.Response) (*GetUsersUserIdDailyMenusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUsersUserIdDailyMenusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DailyMenus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ConstraintsViolationsError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetUsersUserIdDailyMenusDailyMenuIdResponse parses an HTTP response from a GetUsersUserIdDailyMenusDailyMenuIdWithResponse call
func ParseGetUsersUserIdDailyMenusDailyMenuIdResponse(rsp *http.Response) (*GetUsersUserIdDailyMenusDailyMenuIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUsersUserIdDailyMenusDailyMenuIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DailyMenuDetailed
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ConstraintsViolationsError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetUsersUserIdMenusResponse parses an HTTP response from a GetUsersUserIdMenusWithResponse call
func ParseGetUsersUserIdMenusResponse(rsp *http.Response) (*GetUsersUserIdMenusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUsersUserIdMenusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Menus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ConstraintsViolationsError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetUsersUserIdMenusMenuIdResponse parses an HTTP response from a GetUsersUserIdMenusMenuIdWithResponse call
func ParseGetUsersUserIdMenusMenuIdResponse(rsp *http.Response) (*GetUsersUserIdMenusMenuIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUsersUserIdMenusMenuIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MenuDetailed
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ConstraintsViolationsError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetUsersUserIdRecipesResponse parses an HTTP response from a GetUsersUserIdRecipesWithResponse call
func ParseGetUsersUserIdRecipesResponse(rsp *http.Response) (*GetUsersUserIdRecipesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUsersUserIdRecipesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Recipes
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ConstraintsViolationsError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetUsersUserIdRecipesRecipeIdResponse parses an HTTP response from a GetUsersUserIdRecipesRecipeIdWithResponse call
func ParseGetUsersUserIdRecipesRecipeIdResponse(rsp *http.Response) (*GetUsersUserIdRecipesRecipeIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUsersUserIdRecipesRecipeIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RecipeDetailed
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ConstraintsViolationsError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List users
	// (GET /admin/users)
	GetAdminUsers(c *gin.Context)
	// List products
	// (GET /products)
	GetProducts(c *gin.Context)
	// View product
	// (GET /products/{product_id})
	GetProductsProductId(c *gin.Context, productId ProductID)
	// View product's nutrition facts
	// (GET /products/{product_id}/nutrition-facts)
	GetProductsProductIdNutritionFacts(c *gin.Context, productId ProductID)
	// View user
	// (GET /users/{user_id})
	GetUsersUserId(c *gin.Context, userId UserID)
	// List daily menus
	// (GET /users/{user_id}/daily-menus)
	GetUsersUserIdDailyMenus(c *gin.Context, userId UserID)
	// View product
	// (GET /users/{user_id}/daily-menus/{daily_menu_id})
	GetUsersUserIdDailyMenusDailyMenuId(c *gin.Context, userId UserID, dailyMenuId DailyMenuID)
	// List menus
	// (GET /users/{user_id}/menus)
	GetUsersUserIdMenus(c *gin.Context, userId UserID)
	// View product
	// (GET /users/{user_id}/menus/{menu_id})
	GetUsersUserIdMenusMenuId(c *gin.Context, userId UserID, menuId MenuID)
	// List recipes
	// (GET /users/{user_id}/recipes)
	GetUsersUserIdRecipes(c *gin.Context, userId UserID)
	// View recipe
	// (GET /users/{user_id}/recipes/{recipe_id})
	GetUsersUserIdRecipesRecipeId(c *gin.Context, userId UserID, recipeId RecipeID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAdminUsers operation middleware
func (siw *ServerInterfaceWrapper) GetAdminUsers(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAdminUsers(c)
}

// GetProducts operation middleware
func (siw *ServerInterfaceWrapper) GetProducts(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProducts(c)
}

// GetProductsProductId operation middleware
func (siw *ServerInterfaceWrapper) GetProductsProductId(c *gin.Context) {

	var err error

	// ------------- Path parameter "product_id" -------------
	var productId ProductID

	err = runtime.BindStyledParameterWithOptions("simple", "product_id", c.Param("product_id"), &productId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter product_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProductsProductId(c, productId)
}

// GetProductsProductIdNutritionFacts operation middleware
func (siw *ServerInterfaceWrapper) GetProductsProductIdNutritionFacts(c *gin.Context) {

	var err error

	// ------------- Path parameter "product_id" -------------
	var productId ProductID

	err = runtime.BindStyledParameterWithOptions("simple", "product_id", c.Param("product_id"), &productId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter product_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProductsProductIdNutritionFacts(c, productId)
}

// GetUsersUserId operation middleware
func (siw *ServerInterfaceWrapper) GetUsersUserId(c *gin.Context) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId UserID

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", c.Param("user_id"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsersUserId(c, userId)
}

// GetUsersUserIdDailyMenus operation middleware
func (siw *ServerInterfaceWrapper) GetUsersUserIdDailyMenus(c *gin.Context) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId UserID

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", c.Param("user_id"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsersUserIdDailyMenus(c, userId)
}

// GetUsersUserIdDailyMenusDailyMenuId operation middleware
func (siw *ServerInterfaceWrapper) GetUsersUserIdDailyMenusDailyMenuId(c *gin.Context) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId UserID

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", c.Param("user_id"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "daily_menu_id" -------------
	var dailyMenuId DailyMenuID

	err = runtime.BindStyledParameterWithOptions("simple", "daily_menu_id", c.Param("daily_menu_id"), &dailyMenuId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter daily_menu_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsersUserIdDailyMenusDailyMenuId(c, userId, dailyMenuId)
}

// GetUsersUserIdMenus operation middleware
func (siw *ServerInterfaceWrapper) GetUsersUserIdMenus(c *gin.Context) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId UserID

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", c.Param("user_id"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsersUserIdMenus(c, userId)
}

// GetUsersUserIdMenusMenuId operation middleware
func (siw *ServerInterfaceWrapper) GetUsersUserIdMenusMenuId(c *gin.Context) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId UserID

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", c.Param("user_id"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "menu_id" -------------
	var menuId MenuID

	err = runtime.BindStyledParameterWithOptions("simple", "menu_id", c.Param("menu_id"), &menuId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter menu_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsersUserIdMenusMenuId(c, userId, menuId)
}

// GetUsersUserIdRecipes operation middleware
func (siw *ServerInterfaceWrapper) GetUsersUserIdRecipes(c *gin.Context) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId UserID

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", c.Param("user_id"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsersUserIdRecipes(c, userId)
}

// GetUsersUserIdRecipesRecipeId operation middleware
func (siw *ServerInterfaceWrapper) GetUsersUserIdRecipesRecipeId(c *gin.Context) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId UserID

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", c.Param("user_id"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "recipe_id" -------------
	var recipeId RecipeID

	err = runtime.BindStyledParameterWithOptions("simple", "recipe_id", c.Param("recipe_id"), &recipeId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter recipe_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsersUserIdRecipesRecipeId(c, userId, recipeId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/admin/users", wrapper.GetAdminUsers)
	router.GET(options.BaseURL+"/products", wrapper.GetProducts)
	router.GET(options.BaseURL+"/products/:product_id", wrapper.GetProductsProductId)
	router.GET(options.BaseURL+"/products/:product_id/nutrition-facts", wrapper.GetProductsProductIdNutritionFacts)
	router.GET(options.BaseURL+"/users/:user_id", wrapper.GetUsersUserId)
	router.GET(options.BaseURL+"/users/:user_id/daily-menus", wrapper.GetUsersUserIdDailyMenus)
	router.GET(options.BaseURL+"/users/:user_id/daily-menus/:daily_menu_id", wrapper.GetUsersUserIdDailyMenusDailyMenuId)
	router.GET(options.BaseURL+"/users/:user_id/menus", wrapper.GetUsersUserIdMenus)
	router.GET(options.BaseURL+"/users/:user_id/menus/:menu_id", wrapper.GetUsersUserIdMenusMenuId)
	router.GET(options.BaseURL+"/users/:user_id/recipes", wrapper.GetUsersUserIdRecipes)
	router.GET(options.BaseURL+"/users/:user_id/recipes/:recipe_id", wrapper.GetUsersUserIdRecipesRecipeId)
}
